name: AnyMeal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-build-and-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: flex googletest libsqlite3-dev qt6-base-dev-tools qt6-tools-dev-tools qt6-base-dev pkgconf
        version: 1.0
    - name: update path
      run: |
        echo "/usr/lib/qt6/libexec" >> $GITHUB_PATH
        echo "/usr/lib/qt6/bin" >> $GITHUB_PATH
    - name: check path
      run: |
        echo "$PATH"
        ls /usr/lib/qt6/bin	
    - name: autoreconf
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: check
      run: make check
    - name: distributable
      run: make dist-xz
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: anymeal-source
        path: anymeal-*.tar.xz
  fedora-build-and-test:
    name: fedora-build-and-test
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
       dnf -y update
       dnf -y install automake binutils flex gcc-c++ git gtest-devel
       dnf -y install make pkgconf qt6-qtbase-devel qt6-qttools-devel
       dnf -y install sqlite-devel which
    - name: update path
      run: echo "/usr/lib64/qt6/libexec" >> $GITHUB_PATH
    - name: autoreconf
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
  windows-installer:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        release: false
        install: >-
          mingw-w64-x86_64-gcc mingw-w64-x86_64-make autoconf automake make flex bison git libtool
          mingw-w64-x86_64-sqlite3 mingw-w64-x86_64-gtest mingw-w64-x86_64-iconv mingw-w64-x86_64-qt6-base
          mingw-w64-x86_64-qt6-svg mingw-w64-x86_64-qt6-tools mingw-w64-x86_64-qt6-translations
          mingw-w64-x86_64-pkgconf mingw-w64-x86_64-nsis mingw-w64-x86_64-icu mingw-w64-x86_64-libiconv
          mingw-w64-x86_64-pcre mingw-w64-x86_64-pcre2
    - name: autoreconf
      run: ./autogen.sh
    - name: configure
      run: ./configure.mingw
    - name: make
      run: make
    - name: check
      run: make check
    - name: nsis
      run: makensis anymeal.nsi
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: anymeal-installer
        path: anymeal-installer-*.exe
